## Nurullainy binti Mat Rashid 
### Milestone 4: Data Interpretation & Communication of Insights of data

In this part of project all oil prices plus news polarity are combined for the purpose of further analysis such as finding corelation between oil prices trend and news.

In [1]:
import pandas as pd
import numpy as np
from datetime import timedelta

In [2]:
oilprice = pd.read_csv('crudeoil_preprocessed.csv', thousands=',')

In [3]:
print(oilprice.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5053 entries, 0 to 5052
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            5053 non-null   object
 1   Open_Price      5053 non-null   float64
 2   High_Price      5053 non-null   float64
 3   Low_Price       5053 non-null   float64
 4   Close_Price     5053 non-null   float64
 5   Adjusted_Close  5053 non-null   float64
 6   Volume          5053 non-null   int64
dtypes: float64(5), int64(1), object(1)
memory usage: 276.5+ KB
None

In [4]:
len(oilprice)

5053

In [5]:
oilprice['trend'] = ''

In [6]:
# Change Date to date format and reorder dataframe

oilprice['Date'] = pd.to_datetime(oilprice['Date'])
oilprice.sort_values(by=['Date'], ascending=False, inplace=True)
oilprice = oilprice.reset_index(drop=True)
oilprice.dropna(inplace=True)

In [7]:
oilprice.head(10)

,Date,Open_Price,High_Price,Low_Price,Close_Price,Adjusted_Close,Volume,trend
0,2020-12-05,24.379999,26.230000,24.219999,25.160000,25.160000,58355014,
1,2020-12-04,24.600000,24.740000,22.030001,23.129999,23.129999,4624660,
2,2020-12-03,33.070000,33.630001,30.020000,32.980000,32.980000,963502,
3,2020-12-02,49.959999,51.730000,49.950001,51.169998,51.169998,725733,
4,2020-11-05,25.910000,26.730000,24.790001,26.170000,26.170000,397699,
5,2020-11-03,34.619999,36.349998,32.560001,34.360001,34.360001,824665,
6,2020-11-02,49.610001,50.689999,49.580002,49.939999,49.939999,715894,
7,2020-10-05,24.500000,24.750000,24.129999,24.670000,24.670000,324949,
8,2020-10-03,30.370001,35.020000,30.200001,31.129999,31.129999,997569,
9,2020-10-02,50.119999,50.490002,49.419998,49.570000,49.570000,768345,

In [8]:
for i in range(0, len(oilprice)):  # from row 1 untl end of the row
    if oilprice['Close_Price'][i] > oilprice['Close_Price'][i+1]:
        oilprice['trend'][i] = 'upward'
    elif oilprice['Close_Price'][i] == oilprice['Close_Price'][i+1]:
        oilprice['trend'][i] = 'maintain'
    else:
        oilprice['trend'][i] = 'downward'

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

KeyError: 5053

In [9]:
oilprice.isnull().sum()

Date              0
Open_Price        0
High_Price        0
Low_Price         0
Close_Price       0
Adjusted_Close    0
Volume            0
trend             0
dtype: int64

In [10]:
oilprice.head()

,Date,Open_Price,High_Price,Low_Price,Close_Price,Adjusted_Close,Volume,trend
0,2020-12-05,24.379999,26.230000,24.219999,25.160000,25.160000,58355014,upward
1,2020-12-04,24.600000,24.740000,22.030001,23.129999,23.129999,4624660,downward
2,2020-12-03,33.070000,33.630001,30.020000,32.980000,32.980000,963502,downward
3,2020-12-02,49.959999,51.730000,49.950001,51.169998,51.169998,725733,upward
4,2020-11-05,25.910000,26.730000,24.790001,26.170000,26.170000,397699,downward

In [11]:
oilprice['Closing_High'] = ''
oilprice['Closing_Low'] = ''
oilprice['Open_Equals_Closing'] = ''
oilprice['All_Day_Maintain'] = ''

In [13]:
j = i + 1

for i in range(0, len(oilprice) + 1):
    if oilprice['Close_Price'][i] == oilprice['High_Price'][j]:
        i += 1
        oilprice['Closing_High'][i] = 1
    else:
        oilprice['Closing_High'][i] = 0
        
    if oilprice['Close_Price'][i] == oilprice['Low_Price'][j]:
        i += 1
        oilprice['Closing_Low'][i] = 1
    else:
        oilprice['Closing_Low'][i] = 0
        
    if oilprice['Close_Price'][i] == oilprice['Open_Price'][j]:
        i += 1
        oilprice['Open_Equals_Closing'][i] = 1
    else:
        oilprice['Open_Equals_Closing'][i] = 0
    
    if oilprice['Close_Price'][i] == oilprice['Open_Price'][i] == oilprice['High_Price'][i] == oilprice['Low'][i]:
        i += 1
        oilprice['All_Day_Maintain'][i] = 1
    else:
        oilprice['All_Day_Maintain'][i] = 0

for i in range (1,len(goldprice)-1):
    if oilprice['Date'][i] - oilprice['Date'][i+1] == timedelta(days=1):
        continue
    else:
        oilprice = oilprice.append({'Date': oilprice['Date'][i] - timedelta(days=1)}, ignore_index=True)

oilprice.sort_values(by=['Date'], inplace=True)
oilprice = oilprice.reset_index(drop=True)

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

KeyError: 5053

In [14]:
oilprice.head()

,Date,Open_Price,High_Price,Low_Price,Close_Price,Adjusted_Close,Volume,trend,Closing_High,Closing_Low,Open_Equals_Closing,All_Day_Maintain
0,2020-12-05,24.379999,26.230000,24.219999,25.160000,25.160000,58355014,upward,0,0,0,0
1,2020-12-04,24.600000,24.740000,22.030001,23.129999,23.129999,4624660,downward,0,0,0,0
2,2020-12-03,33.070000,33.630001,30.020000,32.980000,32.980000,963502,downward,0,0,0,0
3,2020-12-02,49.959999,51.730000,49.950001,51.169998,51.169998,725733,upward,0,0,0,0
4,2020-11-05,25.910000,26.730000,24.790001,26.170000,26.170000,397699,downward,0,0,0,0

In [15]:
def get_day(x):
    return x.day_name()


def get_day_no(x):
    return x.weekday() + 1


def get_month(x):
    return x.month_name()

In [16]:
oilprice['day'] = oilprice['Date'].apply(get_day)
oilprice['day_no'] = oilprice['Date'].apply(get_day_no)
oilprice['month'] = oilprice['Date'].apply(get_month)
oilprice['year'] = oilprice['Date'].dt.year

In [17]:
oilprice = oilprice[['year', 'month', 'Date', 'day', 'day_no', 
     'Open_Price', 'Low_Price', 'High_Price', 'Close_Price', 
     'trend', 'Open_Equals_Closing', 'All_Day_Maintain', 'Closing_Low', 'Closing_High']]

In [18]:
oilprice.head()

,year,month,Date,day,day_no,Open_Price,Low_Price,High_Price,Close_Price,trend,Open_Equals_Closing,All_Day_Maintain,Closing_Low,Closing_High
0,2020,December,2020-12-05,Saturday,6,24.379999,24.219999,26.230000,25.160000,upward,0,0,0,0
1,2020,December,2020-12-04,Friday,5,24.600000,22.030001,24.740000,23.129999,downward,0,0,0,0
2,2020,December,2020-12-03,Thursday,4,33.070000,30.020000,33.630001,32.980000,downward,0,0,0,0
3,2020,December,2020-12-02,Wednesday,3,49.959999,49.950001,51.730000,51.169998,upward,0,0,0,0
4,2020,November,2020-11-05,Thursday,4,25.910000,24.790001,26.730000,26.170000,downward,0,0,0,0

In [19]:
oilprice.to_csv('oilprice_trend.csv', index=False)

In [20]:
for i in range(0,len(oilprice)):
    if np.isnan(oilprice['Close_Price'][i]):
        oilprice['Close_Price'][i] = np.mean([oilprice['Close_Price'][i-1],oilprice['Close_Price'][i+1]])
    if np.isnan(oilprice['Open_Price'][i]):
        oilprice['Open_Price'][i] = np.mean([oilprice['Open_Price'][i-1],oilprice['Open_Price'][i+1]])
    if np.isnan(oilprice['Low_Price'][i]):
        oilprice['Low_Price'][i] = np.mean([oilprice['Low_Price'][i-1],oilprice['Low_Price'][i+1]])
    if np.isnan(oilprice['High_Price'][i]):
        oilprice['High_Price'][i] = np.mean([oilprice['High_Price'][i-1],oilprice['High_Price'][i+1]])

In [21]:
print(oilprice.shape)

(5053, 14)

In [22]:
# Call news data csv

get_polarity_mean = pd.read_csv('polarity_mean.csv')
get_polarity_mean['Date'] = pd.to_datetime(get_polarity_mean['Date'])

In [23]:
merge = pd.merge(get_polarity_mean,
                 oilprice[['Date','trend']],
                 how='left',
                 left_on=['Date'],
                right_on=['Date'])

In [24]:
merge = merge.reset_index(drop=True)
merge.dropna(how='any', inplace=True)

In [25]:
merge.head()

        Date  polarity_mean   trend
0 2019-01-11      -0.030081  upward
3 2019-02-12       0.008350  upward
5 2019-03-12       0.043914  upward
6 2019-04-11       0.066383  upward
7 2019-04-12      -0.028301  upward

In [26]:
merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 0 to 199
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           150 non-null    datetime64[ns]
 1   polarity_mean  150 non-null    float64
 2   trend          150 non-null    object
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 4.7+ KB

In [27]:
merge.to_csv('oilprice_newspolarity.csv', index=False)